# nixpacks.toml
providers = ["php", "node"]

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_18", "npm-9_x"]
aptPkgs = ["libmysqlclient-dev"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "composer install --optimize-autoloader --no-dev",
    "npm install"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"